
// Get all contacts
GET http://localhost:3000/contacts

###

GET https://amy-baker-cse-341.herokuapp.com/contacts

###
// Get Contacts by ID
GET http://localhost:3000/contacts/626b5d49d8e61d43e6713268

###

GET https://amy-baker-cse-341.herokuapp.com/contacts/626b5cedd8e61d43e6713264


#####
// Add Contact
POST http://localhost:3000/contacts HTTP/1.1
Content-Type : application-json
  
  {
      "firstName":"Davie",
    "lastName":"Jones",
    "email":"bestCat@cat.com",
    "favoriteColor":"Black",
    "birthday":"2/22/2022"
  }

#####
//Modify Contact
PUT http://localhost:3000/contacts/62746a3af8eec7e91e6a28e4 HTTP/1.1
Content-Type:application-json

  {
      "firstName":"modified",
    "lastName":"Contact",
    "email":"bestCat@cat.com",
    "favoriteColor":"Black",
    "birthday":"2/22/2022"
  }


####
DELETE http://localhost:3000/contacts/6275a4311f8dd6ed83cf1ca2 HTTP/1.1
Content-Type:application-json



