
// Get all contacts
GET http://localhost:3000/learnCRUD

GET https://amy-baker-cse-341.herokuapp.com/contacts

###
// Get Contacts by ID
GET http://localhost:3000/contacts/626b5d49d8e61d43e6713268

GET https://amy-baker-cse-341.herokuapp.com/contacts/626b5cedd8e61d43e6713264


#####
// Add Contact
POST http://localhost:3000/learnCRUD HTTP/1.1
Content-Type:application-json
  
  {
      "firstName":"Davie",
    "lastName":"Jones5",
    "email":"bestCat@cat.com",
    "favoriteColor":"Black",
    "birthday":"2/22/2022"
  }

#####
//Modify Contact
PUT http://localhost:3000/learnCRUD/62758b2d09ddefe25baa742d HTTP/1.1
Content-Type:application-json

  {
      "firstName":"modified",
    "lastName":"Contact",
    "email":"bestCat@cat.com",
    "favoriteColor":"Black",
    "birthday":"2/22/2022"
  }


####
DELETE http://localhost:3000/learnCRUD/62746c4041b599dad4fd6566 HTTP/1.1
Content-Type:application-json



