GET http://localhost:3000/contacts

###

GET http://localhost:3000/contacts/626b5cc4d8e61d43e6713262

###

GET https://amy-baker-cse-341.herokuapp.com/contacts

###

GET https://amy-baker-cse-341.herokuapp.com/contacts/626b5cc4d8e61d43e6713262


